### PR TITLE
Fixed a crash by initializing out parameter of aws_mqtt_topic_tree_transaction_remove()

### PR DESCRIPTION
**Pull request by kankri**
This PR fixes the following crash:

```
[TRACE] [2019-12-20T13:40:05Z] [22736] [tls-handler] - id=00FDE528: Processing incomming messages. Downstream window is 4294967295
(9c18.58d0): Access violation - code c0000005 (first chance)
First chance exceptions are reported before any exception handling.
This exception may be expected and handled.
*** WARNING: Unable to verify checksum for aws-crt-cpp-mqtt-pub-sub.exe
aws_crt_cpp_mqtt_pub_sub!s_unsubscribe_send+0x158:
00d33f18 8a4820          mov     cl,byte ptr [eax+20h]      ds:002b:ccccccec=??
0:005:x86> k
ChildEBP RetAddr
02e5efc0 00d40f01 aws_crt_cpp_mqtt_pub_sub!s_unsubscribe_send+0x158 [aws-crt-cpp\deps\build\src\awscmqtt\source\client.c @ 1897]
02e5f04c 00d8f785 aws_crt_cpp_mqtt_pub_sub!s_request_timeout_task+0x301 [aws-crt-cpp\deps\build\src\awscmqtt\source\client_channel_handler.c @ 683]
02e5f090 00dbd0bb aws_crt_cpp_mqtt_pub_sub!s_schedule_cross_thread_tasks+0xd5 [aws-crt-cpp\deps\build\src\awscio\source\channel.c @ 490]
02e5f0ac 00dbda39 aws_crt_cpp_mqtt_pub_sub!aws_task_run+0xbb [aws-crt-cpp\deps\build\src\awsccommon\source\task_scheduler.c @ 53]
02e5f12c 00dbd790 aws_crt_cpp_mqtt_pub_sub!s_run_all+0x1e9 [aws-crt-cpp\deps\build\src\awsccommon\source\task_scheduler.c @ 256]
02e5f144 00d9495b aws_crt_cpp_mqtt_pub_sub!aws_task_scheduler_run_all+0x30 [aws-crt-cpp\deps\build\src\awsccommon\source\task_scheduler.c @ 195]
02e5f844 00dbc239 aws_crt_cpp_mqtt_pub_sub!s_event_thread_main+0x56b [aws-crt-cpp\deps\build\src\awscio\source\windows\iocp\iocp_event_loop.c @ 689]
02e5f884 74708494 aws_crt_cpp_mqtt_pub_sub!thread_wrapper_fn+0x59 [aws-crt-cpp\deps\build\src\awsccommon\source\windows\thread.c @ 45]
02e5f898 77ae41c8 KERNEL32!BaseThreadInitThunk+0x24
02e5f8e0 77ae4198 ntdll_77a80000!__RtlUserThreadStart+0x2f
02e5f8f0 00000000 ntdll_77a80000!_RtlUserThreadStart+0x1b
0:005:x86> dv
           topic = 0xcccccccc
      message_id = 2
is_first_attempt = true
        userdata = 0x010332d8
     transaction = struct aws_array_list
 transaction_buf = 0x02e5ef10 ""
         message = 0x00000000
      num_topics = 1
        task_arg = 0x010332d8
0:005:x86>
```
As can be seen, the crash happens while accessing `topic` in [client.c at line 1897](https://github.com/awslabs/aws-c-mqtt/blob/c6544b60be0b931c499bc3d002e0302640e33a23/source/client.c#L1897) because it's uninitialized. This is because when `aws_mqtt_topic_tree_transaction_remove()` gets to [line L754](https://github.com/awslabs/aws-c-mqtt/blob/c6544b60be0b931c499bc3d002e0302640e33a23/source/topic_tree.c#L754) it exits with `AWS_OP_SUCCESS` without initializing `old_userdata`. However, the caller assumes the when `aws_mqtt_topic_tree_transaction_remove()` succeeds, `old_userdata` contains valid data.

There seem to be 3 ways `aws_mqtt_topic_tree_transaction_remove()` can return:
   * returning an error
   * finding a node and returning `AWS_OP_SUCCESS`
   * NOT finding a node and returning `AWS_OP_SUCCESS`

To distinguish the last two cases, this PR sets `old_userdata` to NULL when a node was not found and adds corresponding checks to the callers.

The mqtt_pub_sub sample program was recently moved to `aws-iot-device-sdk-cpp-v2` which fails to build on Windows. So the crash can be reporoduced by reverting the removal of the mqtt_pub_sub sample (commit 1733dc) and modifying it as follows:

```diff
diff --git a/samples/mqtt_pub_sub/main.cpp b/samples/mqtt_pub_sub/main.cpp
index 8be1282..d48c9e9 100644
--- a/samples/mqtt_pub_sub/main.cpp
+++ b/samples/mqtt_pub_sub/main.cpp
@@ -331,6 +334,7 @@ int main(int argc, char *argv[])
             conditionVariable.notify_one();
         };

+/*
         connection->Subscribe(topic.c_str(), AWS_MQTT_QOS_AT_LEAST_ONCE, onPublish, onSubAck);
         conditionVariable.wait(uniqueLock);

@@ -348,7 +352,8 @@ int main(int argc, char *argv[])
             {
                 break;
             }
-
+*/
+            String input = "hello";
             ByteBuf payload = ByteBufNewCopy(DefaultAllocator(), (const uint8_t *)input.data(), input.length());
             ByteBuf *payloadPtr = &payload;

@@ -365,7 +370,7 @@ int main(int argc, char *argv[])
                 }
             };
             connection->Publish(topic.c_str(), AWS_MQTT_QOS_AT_LEAST_ONCE, false, payload, onPublishComplete);
-        }
+//        }

         /*
          * Unsubscribe from the topic.
```

---
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by bretambrose** [comment]
Thanks for tracking this down.  I'll probably take a deeper look at this tomorrow but the only possible change I would make is rather than conditionally initializing the output param to null in one of the label cases, either assigning it to null at before the call (if only called from one spot) or assigning it to null at the top of the function.  That change would be a little easier to reason about from an invariant standpoint.

**Comment by kankri** [comment]
Personally I usually try to initialize out parameters to safe default values at the start of the function, but here I tried to follow the existing coding style. I can change that. I think leaving the initialization to the caller is error prone (as shown by this crash) and makes it harder to use the function correctly.

**Comment by kankri** [comment]
I was on vacation and just now checked the status of this PR. I'm not seeing any changes or comments. @bretambrose: is there anything I need to do?

**Comment by bretambrose** [comment]
> I was on vacation and just now checked the status of this PR. I'm not seeing any changes or comments. @bretambrose: is there anything I need to do?

The original s2n build error has been fixed, but a new one has been introduced in the meantime.  I have a PR for it at https://github.com/awslabs/s2n/pull/1371

**Comment by bretambrose** [comment]
Merged as part of https://github.com/awslabs/aws-c-mqtt/pull/122.

Thanks for your help!

**Pull request closed without merging**
