### PR TITLE
Update README to accurately reflect what is copied

### PR DESCRIPTION
**Pull request by Octogonapus**
The README was not updated when changes were made to copy parameters such as the topic filter and payload for various functions.
This PR fixes those instances so that the documentation is accurate.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by bretambrose** [comment]
Honestly, most of that README should be removed.  We don't want people using the 311 implementation and this is not a stable API in general.

**Comment by Octogonapus** [comment]
Why don't you want people using the v3.1.1 implementation? The AWS broker still supports v3.1.1. Is it being phased out in favor of the v5 to v3.1.1 adapter?

**Comment by bretambrose** [comment]
> Why don't you want people using the v3.1.1 implementation? The AWS broker still supports v3.1.1. Is it being phased out in favor of the v5 to v3.1.1 adapter?

Nothing's being phased out at the moment.

The 311 implementation was the first client that got written on top of the CRT event loop APIs.  As such it has a lot of properties/decisions that we've come to regret.
* The public API exposes things that it has no business doing (synchronous packet id allocation, for example).  Other properties (per-subscription callbacks, for example) are nice features in theory, but they do not belong in the low-level protocol client.
* The implementation makes heavy usage of shared state and the locking around that state is a nightmare to reason about.  I dread anything that forces me to make changes in the 311 implementation.
* The delicate shared state usage makes it much harder to add new features.

In my ideal world, everyone would use the 5 client.  It's not perfect (as I work on another rust MQTT client as a personal project, I keep finding small things that could be improved) but it is much more maintainable and easy to reason about.  Maybe someday we can extend the current 5 client to also have a 311 mode while keeping the current API contract and sunset the 311 implementation, but that's just a pipe dream atm.

**Comment by Octogonapus** [comment]
Thank you for explaining that!

**Pull request closed without merging**
